# The number of spaces to indent postings
indent: 2

# A metadata key that specifies metadata that should become the auxiliary date of a transaction or posting (date2 in hledger).
auxdate: aux-date

# A metadata key that specifies metadata that should become the date of a posting (date in hledger).
postdate: date
